title: Monikas webpage
author: Monika Siewierska
email: monika.siewierska1@gmail.com
description: #> # this means to ignore newlines until "baseurl:"
This site gives basic information about Monika Siewierska, her skills and hobbies.

theme: minima

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  MonikaSiewierska # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
